### ISSUE TITLE
User Data Management

### ISSUE THREAD

**Issue by matteodem** [sounds-social/sounds-social#101]
Export (JSON file) and Delete Option for User Data

On Delete remind user about passphrase and what everything is inaccessible after deletion (list of urls / files + data)

* [x] Create settings page
* [x] Display settings button on user profile
* [x] Have export section that downlods a JSON file with user data in it
* [x] Create delete button
  * [x] Display modal with explanation of what will be deleted forever (mongo data) and what is still accessible through IPFS with passphrase
  * [x] Next modal display passphrase + explanation and after confirming again delete user data
