### ISSUE TITLE
Alias member managament

### ISSUE THREAD

**Issue by matteodem** [sounds-social/sounds-social#34]
Add a user search input to alias form. Also introduce simple permissions per user.

Have two roles for now: Member (only view), Administrator (view, upload sound, manage members)

How to let people know that they're invited?

## TODO

* [x] Create searchUser graphql query
* [x] Add user multiselect to alias form
* [x] Once somebody invited display them as "invited" in the form
* [x] Display "You're invited" text with buttons (Accept, Deny) on alias detail

**Comment by matteodem** [comment]
@see 7
