### ISSUE TITLE
Upload all files on IPFS with encryption

### ISSUE THREAD

**Issue by matteodem** [sounds-social/sounds-social#53]
* https://ipfs.io/
* https://gist.github.com/chris-rock/335f92742b497256982a
* https://nodejs.org/api/crypto.html
* https://github.com/ipfs/notes/issues/270
* https://medium.com/@mycoralhealth/learn-to-securely-share-files-on-the-blockchain-with-ipfs-219ee47df54c 

Store unique passphrase for each user that is used for encryption. Or PKI. Reuse the existing file collection logic and "swap out" the backend for IPFS instead of graphcool.

## TODO 

* [x] Add box-shadow to homepage (login)
* [x] Check if there's a library or services already out there who covers this
  * https://www.npmjs.com/package/libp2p-keychain
  * https://github.com/libp2p/go-libp2p/issues/64
  * https://www.npmjs.com/package/ipfsecret
* [x] Decide on how to do encryption
  * Do it always? Only do it if user agrees to it?
* [x] Run ipfs daemon locally (and check if doable on Galaxy)
* [x] Use https://github.com/VeliovGroup/Meteor-Files
* [x] Add logic to upload file to IPFS
* [x] Make files retrievable through IPFS (switch out file storage logic)
* [x] Adjust Web UI to upload to server
* [x] Refactor uploading sounds and images
* [x] Add gzip / unzip step to ipfs file storage
* [x] Remove graphcool credentials + on graphcool delete app
* [x] Use https://github.com/zricethezav/gitleaks
* [x] Test extensively

**Comment by matteodem** [comment]
For PKI use https://github.com/JoshKaufman/ursa
